# --------------------------------------------------------------------
# -- Unit Tests for style function
# -- Generated by Zulu
# --------------------------------------------------------------------
import sys
from unittest.mock import MagicMock, patch, PropertyMock
import pytest

# Import the style function from main module
from main import style


class TestStyle:
    """Test suite for the style function."""

    def test_style_sets_stylesheet_with_correct_content(self):
        """Test that style function sets the correct stylesheet."""
        # Create mock QApplication
        mock_app = MagicMock()
        
        # Call style function
        style(mock_app)
        
        # Verify setStyleSheet was called with expected stylesheet
        mock_app.setStyleSheet.assert_called_once()
        stylesheet = mock_app.setStyleSheet.call_args[0][0]
        
        # Verify stylesheet contains expected rules
        assert "QMainWindow::separator {width: 1px}" in stylesheet
        assert "QMenu::separator {height: 1px; margin-left: 6px; margin-right: 6px; background: rgba(155, 155, 155, 255);}" in stylesheet
        assert "QMessageBox {color: white;}" in stylesheet
        assert "QMessageBox QLabel {color: yellow;}" in stylesheet

    def test_style_sets_fusion_style(self):
        """Test that style function sets Fusion style."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        mock_app.setStyle.assert_called_once()
        style_arg = mock_app.setStyle.call_args[0][0]
        assert str(style_arg) == "Fusion"

    def test_style_sets_palette_with_correct_colors_normal_state(self):
        """Test that style function sets palette with correct colors for normal state."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        # Verify setPalette was called
        mock_app.setPalette.assert_called_once()
        palette = mock_app.setPalette.call_args[0][0]
        
        # Verify normal state colors (RGB values)
        from PySide6.QtGui import QPalette, QColor
        
        # Text colors
        assert palette.color(QPalette.ColorRole.Text) == QColor(255, 255, 255)
        assert palette.color(QPalette.ColorRole.WindowText) == QColor(255, 255, 255)
        assert palette.color(QPalette.ColorRole.ButtonText) == QColor(255, 255, 255)
        
        # Background colors
        assert palette.color(QPalette.ColorRole.Window) == QColor(50, 50, 50)
        assert palette.color(QPalette.ColorRole.Button) == QColor(50, 50, 50)
        assert palette.color(QPalette.ColorRole.Base) == QColor(25, 25, 25)
        assert palette.color(QPalette.ColorRole.AlternateBase) == QColor(50, 50, 50)
        
        # Tooltip colors
        assert palette.color(QPalette.ColorRole.ToolTipBase) == QColor(200, 200, 200)
        assert palette.color(QPalette.ColorRole.ToolTipText) == QColor(50, 50, 50)
        
        # Special colors
        assert palette.color(QPalette.ColorRole.BrightText) == QColor(255, 50, 50)
        assert palette.color(QPalette.ColorRole.Link) == QColor(40, 130, 220)

    def test_style_sets_palette_with_correct_colors_disabled_state(self):
        """Test that style function sets palette with correct colors for disabled state."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        # Get the palette that was set
        palette = mock_app.setPalette.call_args[0][0]
        
        from PySide6.QtGui import QPalette, QColor
        
        # Verify disabled state colors
        assert palette.color(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text) == QColor(99, 99, 99)
        assert palette.color(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText) == QColor(99, 99, 99)
        assert palette.color(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText) == QColor(99, 99, 99)
        assert palette.color(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight) == QColor(80, 80, 80)
        assert palette.color(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText) == QColor(99, 99, 99)

    def test_style_sets_font_with_correct_point_size(self):
        """Test that style function sets font with correct point size."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        mock_app.setFont.assert_called_once()
        font = mock_app.setFont.call_args[0][0]
        
        assert font.pointSize() == 10

    def test_style_calls_all_required_methods(self):
        """Test that style function calls all required QApplication methods."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        # Verify all methods were called
        assert mock_app.setStyleSheet.called
        assert mock_app.setStyle.called
        assert mock_app.setPalette.called
        assert mock_app.setFont.called

    def test_style_with_none_application(self):
        """Test that style function handles None application gracefully."""
        mock_app = MagicMock()
        # Simulate None behavior when accessing properties
        mock_app.setStyleSheet.side_effect = AttributeError("setStyleSheet not available")
        
        with pytest.raises(AttributeError):
            style(mock_app)

    def test_style_with_custom_palette_colors(self):
        """Test style function with custom palette color values (boundary testing)."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        from PySide6.QtGui import QPalette, QColor
        
        palette = mock_app.setPalette.call_args[0][0]
        
        # Test boundary values for colors
        # White color boundary
        assert palette.color(QPalette.ColorRole.Text) == QColor(255, 255, 255)
        # Black color boundary (should not be used in this palette)
        # Mid-range colors (50, 50, 50)
        assert palette.color(QPalette.ColorRole.Window) == QColor(50, 50, 50)
        # Light colors (200, 200, 200)
        assert palette.color(QPalette.ColorRole.ToolTipBase) == QColor(200, 200, 200)
        # Special accent colors
        assert palette.color(QPalette.ColorRole.Link) == QColor(40, 130, 220)
        assert palette.color(QPalette.ColorRole.BrightText) == QColor(255, 50, 50)

    def test_style_method_call_order(self):
        """Test that style function calls methods in expected order."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        # Get the order of method calls
        calls = mock_app.method_calls
        method_names = [call[0] for call in calls]
        
        # Verify order: setStyleSheet -> setStyle -> setPalette -> setFont
        assert 'setStyleSheet' in method_names[0]
        assert 'setStyle' in method_names[1]
        assert 'setPalette' in method_names[2]
        assert 'setFont' in method_names[3]

    def test_style_with_multiple_color_role_assignments(self):
        """Test that all ColorRole assignments in the function are correctly applied."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        from PySide6.QtGui import QPalette, QColor
        
        palette = mock_app.setPalette.call_args[0][0]
        
        # Count the number of setColor calls for normal state
        # We expect 11 normal color role assignments + 5 disabled assignments = 16 total
        # Since we can't easily count mock calls, we verify specific color values
        
        # Normal state roles (11 assignments in the function)
        expected_normal_roles = {
            QPalette.ColorRole.Text: QColor(255, 255, 255),
            QPalette.ColorRole.WindowText: QColor(255, 255, 255),
            QPalette.ColorRole.Window: QColor(50, 50, 50),
            QPalette.ColorRole.Button: QColor(50, 50, 50),
            QPalette.ColorRole.Base: QColor(25, 25, 25),
            QPalette.ColorRole.AlternateBase: QColor(50, 50, 50),
            QPalette.ColorRole.ToolTipBase: QColor(200, 200, 200),
            QPalette.ColorRole.ToolTipText: QColor(50, 50, 50),
            QPalette.ColorRole.ButtonText: QColor(255, 255, 255),
            QPalette.ColorRole.BrightText: QColor(255, 50, 50),
            QPalette.ColorRole.Link: QColor(40, 130, 220),
        }
        
        for role, expected_color in expected_normal_roles.items():
            assert palette.color(role) == expected_color, f"Color mismatch for {role}"

    def test_style_with_disabled_color_group_assignments(self):
        """Test that all disabled ColorGroup assignments are correctly applied."""
        mock_app = MagicMock()
        
        style(mock_app)
        
        from PySide6.QtGui import QPalette, QColor
        
        palette = mock_app.setPalette.call_args[0][0]
        
        # Disabled state roles (5 assignments in the function)
        expected_disabled_roles = {
            QPalette.ColorRole.Text: QColor(99, 99, 99),
            QPalette.ColorRole.WindowText: QColor(99, 99, 99),
            QPalette.ColorRole.ButtonText: QColor(99, 99, 99),
            QPalette.ColorRole.Highlight: QColor(80, 80, 80),
            QPalette.ColorRole.HighlightedText: QColor(99, 99, 99),
        }
        
        for role, expected_color in expected_disabled_roles.items():
            actual_color = palette.color(QPalette.ColorGroup.Disabled, role)
            assert actual_color == expected_color, f"Disabled color mismatch for {role}"


if __name__ == '__main__':
    pytest.main([__file__, '-v'])