site_name: User Guide
use_directory_urls: true
theme:
  name: material
  navigation_depth: 10

plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'

extra:
  generator: false
